### ISSUE TITLE
Cannot apply themes

### ISSUE THREAD

**Issue by excusemeflo** [revblaze/AppleMusicUltra#3]
The "apply" tab stays grey'd out and none of the themes transfer to the music player window and only change in the preference window.

**Comment by revblaze** [comment]
I’ll get to fixing that this weekend; however, you can still apply themes directly to Apple Music, in the main window, through the Style and Theme menu bar items!

**Comment by excusemeflo** [comment]
Thanks for the response.  I should've edited my post as right after I sent it I realized using the menu bar worked.  Loving the app!

**Comment by revblaze** [comment]
Glad to hear it! I uploaded the latest release with a main window customizer. You can find it in the README!

Will push the code to Ultra within a few days. :)
